package sandbox

import (
	"fmt"
	"os/exec"
	"strings"
)

// sandboxExec is resolved absolutely, never through PATH.
const sandboxExec = "/usr/bin/sandbox-exec"

// darwinWrap rewrites cmd to run under seatbelt.
//
// The profile is passed with -p (argv), never -f (a temp file). A profile file
// is a TOCTOU target: any same-user process — including the agent we are about
// to confine, if an earlier run left one alive — can rewrite it between our
// WriteFile and sandbox-exec's open. Passing it in argv puts it in memory the
// kernel copies at execve, with no window. The profile contains paths, not
// secrets, so its visibility in `ps` costs nothing, and it removes a cleanup
// path from a command that already juggles cleanup on the os.Exit branch.
//
// sandbox-exec execve()s the target rather than supervising it, so the resulting
// PID *is* the child: signal forwarding and exit codes are byte-identical to an
// unsandboxed exec, and the sandbox is inherited by every descendant and can
// only be narrowed, never widened.
func darwinWrap(spec Spec, cmd *exec.Cmd) error {
	profile, err := renderSBPL(spec)
	if err != nil {
		return err
	}
	args := append([]string{"sandbox-exec", "-p", profile, cmd.Path}, cmd.Args[1:]...)
	cmd.Path = sandboxExec
	cmd.Args = args
	return nil
}

// renderSBPL builds the seatbelt profile.
//
// It emits ONLY (literal ...) and (subpath ...) — never (regex ...). Inside a
// double-quoted SBPL string exactly two bytes are special, backslash and quote;
// spaces, parentheses, semicolons, # and every regex metacharacter are inert.
// With no regex in the profile there is no metacharacter surface to get wrong.
// The deny-default islands below are partly what keeps it that way: they are
// what removed the need to pattern-match rotated audit segments.
func renderSBPL(spec Spec) (string, error) {
	var b strings.Builder
	w := func(format string, a ...interface{}) { fmt.Fprintf(&b, format+"\n", a...) }

	w("(version 1)")
	w("")
	w(";; Generated by akasha — do not edit.")
	w(";; Allow-by-default: an agent needs the whole machine. What follows takes")
	w(";; away only akasha's enumerable secret surface.")
	w("(allow default)")
	w("")

	// ── Denies ──────────────────────────────────────────────────────────────
	// Emitted before every allow, because SBPL is last-match-wins and the
	// allow-backs must be able to punch holes in these.
	for _, r := range spec.Deny {
		if r.Why != "" {
			w(";; %s", sanitizeComment(r.Why))
		}
		verbs := "file-read* file-write*"
		if r.Mode == DenyWrite {
			verbs = "file-write*"
		}
		for _, p := range canonicalVariants(r.Path) {
			q, err := sbplString(p)
			if err != nil {
				return "", err
			}
			form := "literal"
			if r.Tree {
				form = "subpath"
			}
			w("(deny %s (%s %s))", verbs, form, q)
		}
	}

	if spec.DenyKeychain {
		w("")
		w(";; The OS keychain. securityd is the ONLY path to a keychain item, so")
		w(";; denying the mach service closes `security find-generic-password`,")
		w(";; git's osxkeychain helper, and every SecItemCopyMatching at once.")
		w(";; com.apple.trustd is deliberately NOT denied: it evaluates TLS chains,")
		w(";; and the agent must reach its own model API. Network is out of scope.")
		for _, svc := range []string{
			"com.apple.SecurityServer",
			"com.apple.securityd",
			"com.apple.securityd.xpc",
			"com.apple.CoreAuthentication.daemon",
			"com.apple.CoreAuthentication.agent",
		} {
			w("(deny mach-lookup (global-name %q))", svc)
		}
	}

	if spec.DenyDeputies {
		w("")
		w(";; Allow-by-default's structural weakness: the child can ask an")
		w(";; UNSANDBOXED process to read a denied path for it. This closes the")
		w(";; cheapest instance (osascript telling Terminal to cat the vault). It")
		w(";; does NOT close the class — launchctl, ssh localhost, the user's own")
		w(";; daemons remain. That is the price of allow-by-default, and it was")
		w(";; the right price: a jail an agent cannot work in gets bypassed.")
		for _, svc := range []string{
			"com.apple.coreservices.appleevents",
			"com.apple.coreservices.launchservicesd",
		} {
			w("(deny mach-lookup (global-name %q))", svc)
		}
	}

	// ── Allow-backs, always last ────────────────────────────────────────────
	if len(spec.AllowSocket)+len(spec.AllowRead)+len(spec.AllowWrite) > 0 {
		w("")
		w(";; Doors held open. SBPL is last-match-wins, so these are emitted after")
		w(";; every deny — enforced by this function's structure, not by callers")
		w(";; ordering Spec.Deny correctly.")
	}
	for _, p := range spec.AllowSocket {
		for _, v := range canonicalVariants(p) {
			q, err := sbplString(v)
			if err != nil {
				return "", err
			}
			// network-outbound with a literal path is connect(2) on a unix
			// socket; file-read-metadata is the path lookup. Deliberately NOT
			// file-read-data: there is nothing to read, and a narrower grant is
			// a smaller mistake later.
			w("(allow network-outbound (literal %s))", q)
			w("(allow file-read-metadata (literal %s))", q)
		}
	}
	for _, p := range spec.AllowRead {
		for _, v := range canonicalVariants(p) {
			q, err := sbplString(v)
			if err != nil {
				return "", err
			}
			w("(allow file-read* (subpath %s))", q)
		}
	}
	for _, p := range spec.AllowWrite {
		for _, v := range canonicalVariants(p) {
			q, err := sbplString(v)
			if err != nil {
				return "", err
			}
			w("(allow file-read* file-write* (subpath %s))", q)
		}
	}

	out := b.String()
	if err := assertWellFormed(out); err != nil {
		return "", err
	}
	return out, nil
}

// sbplString renders p as an SBPL string literal.
//
// This is the one place in the package where a bug is a silent full bypass:
// $HOME is user-influenced routinely (macOS permits quotes and backslashes in
// directory names) and attacker-influenced in exactly the scenario where it
// matters least. Control bytes are REJECTED rather than escaped — they are legal
// in an APFS filename but never occur in a path derived from $HOME plus a fixed
// component, and their TinyScheme lexing is not worth trusting on a hunch.
func sbplString(p string) (string, error) {
	for i := 0; i < len(p); i++ {
		if p[i] < 0x20 || p[i] == 0x7f {
			return "", fmt.Errorf("sandbox: path contains a control byte at offset %d and cannot be "+
				"expressed safely in a sandbox profile: %q", i, p)
		}
	}
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(p); i++ {
		if c := p[i]; c == '\\' || c == '"' {
			b.WriteByte('\\')
		}
		b.WriteByte(p[i])
	}
	b.WriteByte('"')
	return b.String(), nil
}

// sanitizeComment keeps a Why string from ending a comment line early.
func sanitizeComment(s string) string {
	return strings.Map(func(r rune) rune {
		if r == '\n' || r == '\r' {
			return ' '
		}
		return r
	}, s)
}

// stripStrings removes quoted literals (respecting backslash escapes) so the
// remaining text is only SBPL structure.
//
// Counting forms without doing this is wrong in the direction that matters: a
// path legitimately containing the text "(allow default)" would look like an
// injection, and — worse for confidence — an injection that DID escape correctly
// would look identical to one that did not. Structure has to be judged on
// structure.
func stripStrings(profile string) (structure string, unterminated bool) {
	var b strings.Builder
	inStr := false
	for i := 0; i < len(profile); i++ {
		c := profile[i]
		switch {
		case inStr && c == '\\':
			i++ // skip the escaped byte, whatever it is
		case c == '"':
			inStr = !inStr
		case !inStr:
			b.WriteByte(c)
		}
	}
	return b.String(), inStr
}

// assertWellFormed is the renderer checking its own output, judged on the
// profile's STRUCTURE with string literals removed: exactly one (allow default),
// and balanced parentheses. A quote escape that leaked would break both, because
// the leaked text would then be parsed as structure.
func assertWellFormed(profile string) error {
	structure, unterminated := stripStrings(profile)
	if unterminated {
		return fmt.Errorf("sandbox: generated profile has an unterminated string literal")
	}
	if n := strings.Count(structure, "(allow default)"); n != 1 {
		return fmt.Errorf("sandbox: generated profile has %d (allow default) forms in its structure, want exactly 1", n)
	}
	depth := 0
	for i := 0; i < len(structure); i++ {
		switch structure[i] {
		case '(':
			depth++
		case ')':
			depth--
			if depth < 0 {
				return fmt.Errorf("sandbox: generated profile has unbalanced parentheses")
			}
		}
	}
	if depth != 0 {
		return fmt.Errorf("sandbox: generated profile has %d unclosed parentheses", depth)
	}
	return nil
}
